use crate::error::CustomError;
use std::fs;
use std::path::Path;
use texture_packer::TexturePacker;

//sprite
const SPRITE_OUTPUT_DIR: &str = "source/types/game/generated_sprite.odin";
//font
const FONT_SRC_DIR: &str = "assets/fonts";
const FONT_OUT_DIR: &str = "source/types/game/generated_font.odin";
//audio
const AUDIO_SRC_DIR: &str = "assets/audio";
const AUDIO_OUT_DIR: &str = "source/types/game/generated_audio.odin";

//this is separated from generate_asset_metadata, since there's a lot of "custom" logic here
pub fn generate_sprite_metadata(
    packer: &TexturePacker<image::RgbaImage, String>,
    width: u32,
    height: u32,
) -> Result<(), CustomError> {
    let mut odin_code = String::new();

    odin_code.push_str("package game_types\n\n");
    odin_code.push_str("import \"../gmath\"\n\n");
    odin_code.push_str("// NOTE: Don't edit. Generated by CLI.\n");

    odin_code.push_str("SpriteData :: struct {\n");
    odin_code.push_str("\tuv:           gmath.Vec4,\n");
    odin_code.push_str("\tsize:         gmath.Vec2,\n");
    odin_code.push_str("}\n\n");

    odin_code.push_str("SpriteName :: enum {\n");
    odin_code.push_str("\tnil,\n");
    for (key, _) in packer.get_frames() {
        let clean_key = key.replace("-", "_").replace(" ", "_");
        odin_code.push_str(&format!("\t{},\n", clean_key));
    }
    odin_code.push_str("}\n\n");

    odin_code.push_str("getSpriteData :: proc(sprite: SpriteName) -> SpriteData {\n");
    odin_code.push_str("\tswitch sprite {\n");
    let w = width as f32;
    let h = height as f32;
    odin_code.push_str("\tcase .nil: return { gmath.Vec4{0, 0, 0, 0}, gmath.Vec2{0, 0} }\n");
    for (key, frame) in packer.get_frames() {
        let clean_key = key.replace("-", "_").replace(" ", "_");

        let u0 = frame.frame.x as f32 / w;
        let v0 = frame.frame.y as f32 / h;
        let u1 = (frame.frame.x + frame.frame.w) as f32 / w;
        let v1 = (frame.frame.y + frame.frame.h) as f32 / h;

        let px_w = frame.frame.w as f32;
        let px_h = frame.frame.h as f32;

        odin_code.push_str(&format!(
            "\tcase .{}: return {{ gmath.Vec4{{ {:.6}, {:.6}, {:.6}, {:.6} }}, gmath.Vec2{{ {:.1}, {:.1} }} }}\n",
            clean_key, u0, v0, u1, v1, px_w, px_h
        ));
    }

    odin_code.push_str("\t}\n");
    odin_code.push_str("\treturn {gmath.Vec4{0, 0, 0, 0}, gmath.Vec2{0, 0} }\n");
    odin_code.push_str("}\n");

    let output_path = Path::new(SPRITE_OUTPUT_DIR);

    fs::create_dir_all(output_path.parent().unwrap())?;
    fs::write(output_path, odin_code)?;

    Ok(())
}

pub fn generate_assets() -> Result<(), CustomError> {
    generate_asset_metadata(FONT_SRC_DIR, FONT_OUT_DIR, "ttf", "Font")?;
    generate_asset_metadata(AUDIO_SRC_DIR, AUDIO_OUT_DIR, "wav", "Audio")?;
    Ok(())
}

fn generate_asset_metadata(
    asset_src: &str,
    asset_out: &str,
    ext: &str,
    enum_name: &str,
) -> Result<(), CustomError> {
    let asset_dir = Path::new(asset_src);
    let output_file = Path::new(asset_out);

    let mut entries = vec![];
    if asset_dir.exists() {
        for entry in fs::read_dir(asset_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some(ext) {
                let stem = path.file_stem().unwrap().to_str().unwrap(); // this unwrapping is
                // ugly and might cause silent errors, TODO: replace that with proper error
                // handling
                let clean_stem = stem.replace("-", "_").replace(" ", "_");
                let filename = path.file_name().unwrap().to_str().unwrap().to_string();
                entries.push((clean_stem, filename));
            }
        }
    }

    let mut odin_code = String::new();

    odin_code.push_str("package game_types\n\n");

    odin_code.push_str(&format!("{}Name :: enum {{\n", enum_name));
    odin_code.push_str("\tnil,\n");
    for (name, _) in &entries {
        odin_code.push_str(&format!("\t{}, \n", name));
    }
    odin_code.push_str("}\n\n");

    //map for gen
    odin_code.push_str(&format!(
        "{}Filename := [{}Name]string {{\n",
        enum_name.to_lowercase(),
        enum_name
    ));
    odin_code.push_str("\t.nil = \"\",\n");
    for (name, file) in &entries {
        odin_code.push_str(&format!("\t.{} = \"{}\",\n", name, file));
    }
    odin_code.push_str("}\n");

    fs::create_dir_all(output_file.parent().unwrap())?;
    fs::write(output_file, odin_code)?;

    Ok(())
}
