use crate::error::CustomError;
use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::path::Path;
use texture_packer::TexturePacker;
use serde::Serialize;
use crate::packer::{pack_font, GlyphMetrics};
use crate::Ui;
use fontdue::FontSettings;

enum AssetSearchMode<'a> {
    ByExtension(&'a str),
    Directories,
}

#[derive(Serialize)]
pub struct SpriteMetadata {
    pub u0: f32,
    pub v0: f32,
    pub u1: f32,
    pub v1: f32,
    pub size_x: f32,
    pub size_y: f32,
    pub frames: i32,
}

//sprite
const SPRITE_OUTPUT_DIR: &str = "bonsai/generated/sprite.odin";
const SPRITE_BINARY_DIR: &str = ".bonsai/cache/sprites/sprites.bin";
//font
const FONT_SRC_DIR: &str = "assets/fonts";
const FONT_OUT_DIR: &str = "bonsai/generated/font.odin";
const FONT_DATA_OUT_DIR: &str = ".bonsai/cache/fonts";
const ADDITIONAL_FONT_ENUM: &str = "PixelCode";
const ADDITIONAL_FONT_FILENAME: &str = "bonsai/core/render/PixelCode_9.ttf";
const ADDITIONAL_FONT_DIR: &str = "bonsai/core/render";
//audio
const AUDIO_SRC_DIR: &str = "assets/audio";
const AUDIO_OUT_DIR: &str = "bonsai/generated/audio.odin";
//scene
const SCENE_REG_OUT_DIR: &str = "source/game/scenes/generated_registry.odin";
const SCENE_SRC_DIR: &str = "source/game/scenes";
const SCENE_OUT_DIR: &str = "bonsai/generated/scene.odin";

fn clean_key_suffix(mut clean_key: String) -> Result<String, CustomError> {
    if let Some(last_underscore) = clean_key.rfind('_') {
        let suffix = &clean_key[last_underscore + 1..];
        if let Some(x_idx) = suffix.find('x') {
            let left = &suffix[..x_idx];
            let right = &suffix[x_idx + 1..];
            if left.parse::<i32>().is_ok() && right.parse::<i32>().is_ok() {
                clean_key.truncate(last_underscore);
            }
        }
    }
    Ok(clean_key)
}

pub fn parse_font_stem(stem: &str) -> (String, Option<u8>) {
    if let Some(last_underscore) = stem.rfind('_') {
        let suffix = &stem[last_underscore + 1..];
        if let Ok(size) = suffix.parse::<u8>() {
            return (stem[..last_underscore].to_string(), Some(size));
        }
    }
    (stem.to_string(), None)
}

//this is separated from generate_asset_metadata, since there's a lot of "custom" logic here
pub fn generate_sprite_metadata(
    packer: &TexturePacker<image::RgbaImage, String>,
    width: u32,
    height: u32,
    extruded_sprites: &BTreeSet<String>,
) -> Result<Vec<u8>, CustomError> {
    let mut sorted_frames: Vec<_> = packer.get_frames().iter().collect();
    sorted_frames.sort_by_key(|(key, _frame)| *key);
    
    let mut odin_code = String::new();

    odin_code.push_str("// NOTE: Machine generated by bonsai CLI.\n");
    odin_code.push_str("package generated\n\n");

    odin_code.push_str("// @overview\n");
    odin_code.push_str("// This package contains all of the auto-generated data at build-time. Currently it stores:\n");
    odin_code.push_str("// - **Sprite data:** Assigns **atlas UV** and **image size in pixels** to every **PNG** image from **assets/images**.\n");
    odin_code.push_str("//   Manages animation and tileset data. More information on that topic can be found [here](`https://bonsai-framework.dev/reference/core/render/#overview`).\n");
    odin_code.push_str("// - **Font data:** Grabs **TTF/OTF** files present in the `assets/fonts` directory, generates bitmap using the [`stb`](`https://github.com/nothings/stb`) library.\n");
    odin_code.push_str(
        "//   Makes the fonts easily accessible with the [`FontName`](#fontname) enum.\n",
    );
    odin_code.push_str("// - **Audio data:** Grabs **WAV** files present in the `assets/audio` directory and links each sound to a [`SoundName`](#soundname) enum.\n");
    odin_code.push_str("// - **Scene data:** Generates a registry in the `source/game/scenes` directory, which registers all created scenes. Using directory names, generates\n");
    odin_code.push_str("//   a [`SceneName`](#scenename) enum to access them. Example usage can be found [here](`https://bonsai-framework.dev/reference/core/scene/#overview`).\n");

    odin_code.push_str("\n\n");

    odin_code.push_str("import \"bonsai:core/gmath\"\n\n");

    odin_code.push_str("// @ref\n");
    odin_code.push_str("// Struct assigned to every sprite present on the atlas.\n");
    odin_code.push_str("SpriteData :: struct {\n");
    odin_code.push_str("\tuv:           gmath.Vector4,\n");
    odin_code.push_str("\tsize:         gmath.Vector2,\n");
    odin_code.push_str("\tframes:       int,\n");
    odin_code.push_str("}\n\n");

    odin_code.push_str("// @ref\n");
    odin_code.push_str("// Enum containing all sprite file names.\n");
    odin_code.push_str("SpriteName :: enum u32 {\n");
    odin_code.push_str("\tnil,\n");

    let mut metadata_array = Vec::new();
    
    metadata_array.push(SpriteMetadata {
        u0: 0.0, v0: 0.0, u1: 0.0, v1: 0.0,
        size_x: 0.0, size_y: 0.0, frames: 1,
    });

    for (key, frame) in sorted_frames {
        let mut clean_key = key.replace("-", "_").replace(" ", "_");
        clean_key = clean_key_suffix(clean_key)?;

        odin_code.push_str(&format!("\t{},\n", clean_key));

        let mut x = frame.frame.x;
        let mut y = frame.frame.y;
        let mut w = frame.frame.w;
        let mut h = frame.frame.h;

        if extruded_sprites.contains(key) {
            x += 1; y += 1;
            w -= 2; h -= 2;
        }

        let u0 = x as f32 / width as f32;
        let v0 = y as f32 / height as f32;
        let u1 = (x + w) as f32 / width as f32;
        let v1 = (y + h) as f32 / height as f32;

        let mut frames_count = 1;
        let normalized_key = key.replace("-", "_").replace(" ", "_");
        if let Some(last_underscore) = normalized_key.rfind('_') {
            let suffix = &normalized_key[last_underscore + 1..];
            if let Some(x_idx) = suffix.find('x') {
                let frames_str = &suffix[..x_idx];
                if let Ok(f) = frames_str.parse::<i32>() {
                    frames_count = f;
                }
            }
        }

        metadata_array.push(SpriteMetadata {
            u0, v0, u1, v1,
            size_x: w as f32,
            size_y: h as f32,
            frames: frames_count,
        });
    }
    odin_code.push_str("}\n\n");

    let output_path = Path::new(SPRITE_OUTPUT_DIR);
    fs::create_dir_all(output_path.parent().unwrap())?;
    fs::write(output_path, odin_code)?;

    let mut bin_data = Vec::with_capacity(metadata_array.len() * 28); // 7 x f32
    for meta in &metadata_array {
        bin_data.extend_from_slice(&meta.u0.to_le_bytes());
        bin_data.extend_from_slice(&meta.v0.to_le_bytes());
        bin_data.extend_from_slice(&meta.u1.to_le_bytes());
        bin_data.extend_from_slice(&meta.v1.to_le_bytes());
        bin_data.extend_from_slice(&meta.size_x.to_le_bytes());
        bin_data.extend_from_slice(&meta.size_y.to_le_bytes());
        let frames_f32 = meta.frames as f32;
        bin_data.extend_from_slice(&frames_f32.to_le_bytes());
    }

    let bin_path = Path::new(SPRITE_BINARY_DIR);
    if let Some(parent) = bin_path.parent() { fs::create_dir_all(parent)?; }
    fs::write(bin_path, &bin_data)?;

    Ok(bin_data)
}

//like above, too custom to abstract out
fn generate_scene_registry_metadata(scene_src: &str, scene_out: &str) -> Result<(), CustomError> {
    let scene_dir = Path::new(scene_src);
    let registry_file = Path::new(scene_out);

    let mut entries = vec![];
    if scene_dir.exists() {
        for entry in fs::read_dir(scene_dir)? {
            let entry = entry?;
            let path = entry.path();

            if path.is_dir() {
                if let (Some(stem_os), Some(filename_os)) = (path.file_stem(), path.file_name()) {
                    if let (Some(stem), Some(filename)) = (stem_os.to_str(), filename_os.to_str()) {
                        let clean_stem = stem.replace("-", "_").replace(" ", "_");
                        entries.push((clean_stem, filename.to_string()));
                    }
                }
            }
        }
    }

    let mut odin_code = String::new();

    odin_code.push_str("// NOTE: Machine generated by bonsai CLI.\n");
    odin_code.push_str("package scenes\n\n");
    odin_code.push_str("import \"bonsai:core/scene\"\n");
    odin_code.push_str("import \"bonsai:core/scene/type\"\n");
    odin_code.push_str("import \"bonsai:generated\"");
    odin_code.push_str("\n");
    odin_code.push_str("_ :: scene\n");
    odin_code.push_str("_ :: generated\n");
    odin_code.push_str("_ :: type\n");
    odin_code.push_str("\n");
    for (name, _) in &entries {
        odin_code.push_str(&format!("import \"{name}\"\n"));
    }
    odin_code.push_str("\n");
    for (name, _) in &entries {
        odin_code.push_str(&format!(
            "@(private = \"file\")\n_{name}Data: {name}.Data\n"
        ));
    }
    odin_code.push_str("\ninitRegistry :: proc() {\n");
    for (name, _) in &entries {
        odin_code.push_str(&format!("\tscene.register(\n\t\tgenerated.SceneName.{name},\n\t\ttype.Scene{{\n\t\t\tdata=&_{name}Data,\n\t\t\tinit={name}.init,\n\t\t\tupdate={name}.update,\n\t\t\tdraw={name}.draw,\n\t\t\texit={name}.exit,\n\t\t}},\n\t)\n"))
    }
    odin_code.push_str("}");

    if let Some(parent) = registry_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(registry_file, odin_code)?;

    Ok(())
}

// the generate_sprite_metadata should be used instead of a newly created function but its faster
// to do it that way
pub fn generate_empty_sprite_metadata() -> Result<(), CustomError> {
    let mut odin_code = String::new();

    odin_code.push_str("// NOTE: Machine generated by bonsai CLI.\n");
    odin_code.push_str("package generated\n\n");

    odin_code.push_str("// @overview\n");
    odin_code.push_str("// This package contains all of the auto-generated data at build-time. Currently it stores:\n");
    odin_code.push_str("// - **Sprite data:** Assigns **atlas UV** and **image size in pixels** to every **PNG** image from **assets/images**.\n");
    odin_code.push_str("//   Manages animation and tileset data. More information on that topic can be found [here](`https://bonsai-framework.dev/reference/core/render/#overview`).\n");
    odin_code.push_str("// - **Font data:** Grabs **TTF/OTF** files present in the `assets/fonts` directory, generates bitmap using the [`stb`](`https://github.com/nothings/stb`) library.\n");
    odin_code.push_str(
        "//   Makes the fonts easily accessible with the [`FontName`](#fontname) enum.\n",
    );
    odin_code.push_str("// - **Audio data:** Grabs **WAV** files present in the `assets/audio` directory and links each sound to a [`SoundName`](#soundname) enum.\n");
    odin_code.push_str("// - **Scene data:** Generates a registry in the `source/game/scenes` directory, which registers all created scenes. Using directory names, generates\n");
    odin_code.push_str("//   a [`SceneName`](#scenename) enum to access them. Example usage can be found [here](`https://bonsai-framework.dev/reference/core/scene/#overview`).\n");

    odin_code.push_str("\n\n");

    odin_code.push_str("import \"bonsai:core/gmath\"\n\n");

    odin_code.push_str("// @ref\n");
    odin_code.push_str("// Struct assigned to every sprite present on the atlas.\n");
    odin_code.push_str("SpriteData :: struct {\n");
    odin_code.push_str("\tuv:           gmath.Vector4,\n");
    odin_code.push_str("\tsize:         gmath.Vector2,\n");
    odin_code.push_str("\tframes:       int,\n");
    odin_code.push_str("}\n\n");

    odin_code.push_str("// @ref\n");
    odin_code.push_str("// Enum containing all sprite file names.\n");
    odin_code.push_str("SpriteName :: enum u32 {\n");
    odin_code.push_str("\tnil,\n");
    odin_code.push_str("}\n");

    let output_path = Path::new(SPRITE_OUTPUT_DIR);

    fs::create_dir_all(output_path.parent().unwrap())?;
    fs::write(output_path, odin_code)?;

    Ok(())
}

pub fn generate_font_metadata(
    packer: &TexturePacker<image::RgbaImage, String>,
    width: u32,
    height: u32,
    is_pixel: bool,
    native_size: u8,
    metrics_map: &HashMap<char, GlyphMetrics>,
) -> Result<Vec<u8>, CustomError> {
    let mut bin_data = Vec::new();

    bin_data.push(if is_pixel { 1 } else { 0 });
    bin_data.push(native_size);

    for c in 32..127u8 {
        let ch = c as char;
        let key = ch.to_string();

        if let Some(frame) = packer.get_frame(&key) {
            let metrics = metrics_map.get(&ch).unwrap_or(&GlyphMetrics {
                x_offset: 0.0, y_offset: 0.0, advance: 0.0
            });

            let x = frame.frame.x as f32;
            let y = frame.frame.y as f32;
            let w = frame.frame.w as f32;
            let h = frame.frame.h as f32;

            let u0 = x / width as f32;
            let v0 = y / height as f32;
            let u1 = (x + w) / width as f32;
            let v1 = (y + h) / height as f32;

            bin_data.extend_from_slice(&(c as u32).to_le_bytes());

            bin_data.extend_from_slice(&u0.to_le_bytes());
            bin_data.extend_from_slice(&v0.to_le_bytes());
            bin_data.extend_from_slice(&u1.to_le_bytes());
            bin_data.extend_from_slice(&v1.to_le_bytes());

            bin_data.extend_from_slice(&w.to_le_bytes());
            bin_data.extend_from_slice(&h.to_le_bytes());

            bin_data.extend_from_slice(&metrics.x_offset.to_le_bytes());
            bin_data.extend_from_slice(&metrics.y_offset.to_le_bytes());
            bin_data.extend_from_slice(&metrics.advance.to_le_bytes());
        }
    }

    Ok(bin_data)
}

fn build_fonts(font_assets_dir: &Path, font_output_dir: &Path, ui: &Ui) {
    if font_assets_dir.exists() {
        if let Ok(entries) = std::fs::read_dir(&font_assets_dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if let Some(ext) = path.extension() {
                    if ext == "ttf" || ext == "otf" {
                        let raw_stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("unknown");
                        let clean_stem = raw_stem.replace("-", "_").replace(" ", "_");
                        let (final_name, native_size_opt) = parse_font_stem(&clean_stem);

                        let is_pixel = native_size_opt.is_some();
                        let native_size = native_size_opt.unwrap_or(0);

                        if let Err(e) = pack_font(&path, &final_name, is_pixel, native_size, &font_output_dir, ui) {
                            ui.error(&format!("Failed to pack font at build time: {}", e));
                        }
                    }
                }
            }
        }
    } else if ui.verbose {
        ui.log("No fonts directory found, skipping build-time font packing.");
    }
}

pub fn detect_native_size(font_bytes: &[u8], font_name: &str, ui: &Ui) {
    if ui.verbose {
        ui.status(&format!("Analyzing {} to find true pixel size...", font_name));
    }

    let font = match fontdue::Font::from_bytes(font_bytes, FontSettings::default()) {
        Ok(f) => f,
        Err(_) => {
            ui.error("Failed to parse font for size detection.");
            return;
        }
    };

    let mut found_sizes = Vec::new();

    for test_size in 8..=64u8 {
        let (metrics, bitmap) = font.rasterize('@', test_size as f32);

        if metrics.width == 0 || metrics.height == 0 { continue; }

        let mut is_blurry = false;

        for &alpha in &bitmap {
            if alpha > 0 && alpha < 255 {
                is_blurry = true;
                break;
            }
        }

        if !is_blurry {
            found_sizes.push(test_size);
            if ui.verbose {
                ui.log(&format!("Size for font {} found: {}px", font_name, test_size));
            }
        }
    }

    if found_sizes.is_empty() {
        ui.log(&format!("No perfect pixel size found for {}.", font_name));
    } else {
        ui.log(&format!("Recommendation: Rename your file to {}_{}.ttf/otf", font_name, found_sizes[0]));
    }
}

pub fn generate_assets(ui: &Ui) -> Result<(), CustomError> {
    build_fonts(Path::new(FONT_SRC_DIR), Path::new(FONT_DATA_OUT_DIR), ui);
    build_fonts(Path::new(ADDITIONAL_FONT_DIR), Path::new(FONT_DATA_OUT_DIR), ui);
    generate_asset_metadata(
        FONT_SRC_DIR,
        FONT_OUT_DIR,
        ADDITIONAL_FONT_ENUM,
        ADDITIONAL_FONT_FILENAME,
        AssetSearchMode::ByExtension("ttf"),
        "Font",
    )?;
    generate_asset_metadata(
        AUDIO_SRC_DIR,
        AUDIO_OUT_DIR,
        "",
        "",
        AssetSearchMode::ByExtension("wav"),
        "Audio",
    )?;
    generate_asset_metadata(
        SCENE_SRC_DIR,
        SCENE_OUT_DIR,
        "",
        "",
        AssetSearchMode::Directories,
        "Scene",
    )?;
    generate_scene_registry_metadata(SCENE_SRC_DIR, SCENE_REG_OUT_DIR)?;
    Ok(())
}

fn generate_asset_metadata(
    asset_src: &str,
    asset_out: &str,
    additional_asset_enum: &str,
    additional_asset_filename: &str,
    mode: AssetSearchMode,
    enum_name: &str,
) -> Result<(), CustomError> {
    let asset_dir = Path::new(asset_src);
    let output_file = Path::new(asset_out);

    let mut entries: Vec<(String, String, Option<u8>)> = vec![];

    if asset_dir.exists() {
        for entry in fs::read_dir(asset_dir)? {
            let entry = entry?;
            let path = entry.path();

            let is_match = match mode {
                AssetSearchMode::ByExtension(ext) => {
                    path.is_file() && path.extension().and_then(|s| s.to_str()) == Some(ext)
                }
                AssetSearchMode::Directories => path.is_dir(),
            };

            let mut is_match_second = false;
            if enum_name == "Font" {
                is_match_second = match AssetSearchMode::ByExtension("otf") {
                    AssetSearchMode::ByExtension(ext) => {
                        path.is_file() && path.extension().and_then(|s| s.to_str()) == Some(ext)
                    }
                    AssetSearchMode::Directories => path.is_dir(),
                };
            }

            if is_match || is_match_second {
                if let Some(stem_os) = path.file_stem() {
                    if let (Some(stem), Some(path_str)) = (stem_os.to_str(), path.to_str()) {
                        let mut clean_stem = stem.replace("-", "_").replace(" ", "_");
                        let mut size = None;

                        if enum_name == "Font" {
                            let (stripped_stem, extracted_size) = parse_font_stem(&clean_stem);
                            clean_stem = stripped_stem;
                            size = extracted_size;
                        }

                        entries.push((clean_stem, path_str.to_string(), size));
                    }
                }
            }
        }
    }

    // let mut additional_size = None;
    // if !additional_asset_filename.is_empty() && enum_name == "Font" {
    //     if let Some(stem) = Path::new(additional_asset_filename).file_stem().and_then(|s| s.to_str()) {
    //         let (_, extracted_size) = parse_font_stem(stem);
    //         additional_size = extracted_size;
    //     }
    // }

    let mut odin_code = String::new();

    odin_code.push_str("// NOTE: Machine generated by bonsai CLI\n");
    odin_code.push_str("package generated\n\n");

    odin_code.push_str("// @ref\n");
    odin_code.push_str(&format!(
        "// Contains all filename stems for {}s.\n",
        enum_name
    ));
    odin_code.push_str(&format!("{}Name :: enum {{\n", enum_name));
    odin_code.push_str("\tnil,\n");
    if additional_asset_enum != "" && additional_asset_filename != "" {
        odin_code.push_str(&format!("\t{}, \n", additional_asset_enum));
    }
    for (name, _, _) in &entries {
        odin_code.push_str(&format!("\t{}, \n", name));
    }
    odin_code.push_str("}\n\n");

    if let AssetSearchMode::ByExtension(_) = mode {
        //map for gen
        odin_code.push_str("// @ref\n");
        odin_code.push_str(&format!(
            "// Links every `{}Name` enum to their path relative to the project root.\n",
            enum_name
        ));
        odin_code.push_str(&format!(
            "{}Filename := [{}Name]string {{\n",
            enum_name.to_lowercase(),
            enum_name
        ));
        odin_code.push_str("\t.nil = \"\",\n");
        if additional_asset_enum != "" && additional_asset_filename != "" {
            odin_code.push_str(&format!(
                "\t.{} = \"{}\", \n",
                additional_asset_enum, additional_asset_filename
            ));
        }
        for (name, file, _) in &entries {
            odin_code.push_str(&format!("\t.{} = \"{}\",\n", name, file));
        }
        odin_code.push_str("}\n");
    }

    if let Some(parent) = output_file.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output_file, odin_code)?;

    Ok(())
}
